In [311]:
import pandas as pd

In [313]:
#Reading a xlsl file with a list of customers that need to be called
df = pd.read_excel('Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [315]:
#Dropping duplicates from the list

df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [317]:
#Deleting a column that is not necessary 

df= df.drop(columns= 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [319]:
# Removing NA,NaN, N/a and special characters ('./_') from Last_Name columm.

df['Last_Name'] = df['Last_Name'].apply(lambda x: '' if pd.isna(x) or pd.isnull(x) or str(x)=='N/a' else str(x))

df['Last_Name']= df['Last_Name'].str.strip('./_')

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [321]:
#Concatenating columns to create a new Full Name column

df['Full_Name']= df['First_Name']+' '+df['Last_Name']
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,Jeff Winger
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,NaN,Gandalf
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,Creed Braton
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [323]:
#Dropping 'First_Name' and 'Last_Name' columns.

df = df.drop(columns = ['First_Name','Last_Name'], axis=1)
df

,CustomerID,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,NaN,1209 South Street,No,No,Jeff Winger
7,1008,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,N/a,123 Middle Earth,Yes,NaN,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,NaN,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,N/a,N/a,N/a,Yes,Creed Braton
19,1020,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [325]:
#Removing NA and NAN values from the phone_Number column

df['Phone_Number'] = df['Phone_Number'].apply(lambda x: '' if pd.isna(x) or pd.isnull(x) else str(x))
df

,CustomerID,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,N/a,123 Middle Earth,Yes,NaN,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,N/a,N/a,N/a,Yes,Creed Braton
19,1020,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [327]:
#Noticed some "N/a" strings that were not removed.
#Replacing strings with 'N/a' for a blank space.

df['Phone_Number'] = df['Phone_Number'].str.replace('N/a','',regex=True)                                        
df

,CustomerID,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123/643/9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876|678|3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876|678|3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,NaN,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876|678|3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,,N/a,N/a,Yes,Creed Braton
19,1020,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [329]:
#Standardizing phone numbers format

df['Phone_Number'] = df['Phone_Number'].str.replace(r'[^a-zA-Z0-9]','', regex=True)
df

,CustomerID,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,1235455421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,1236439775,93 West Main Street,No,Yes,Abed Nadir
2,1003,7066950392,298 Drugs Driveway,N,NaN,Walter White
3,1004,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,8766783469,123 Dragons Road,Y,No,Jon Snow
5,1006,3047622467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,8766783469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,NaN,Gandalf
9,1010,1235455421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,7066950392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,1235432345,2039 Main Street,Yes,N,Don Draper
13,1014,8766783469,343 City Parkway,Yes,No,Leslie Knope
14,1015,3047622467,214 HR Avenue,N,No,Toby Flenderson
15,1016,1235455421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,7066950392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,,N/a,N/a,Yes,Creed Braton
19,1020,8766783469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [331]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: '' if x=='' else x[0:3]+'-'+x[3:6]+'-'+x[6:10])
df

,CustomerID,Phone_Number,Address,Paying Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123-643-9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,706-695-0392,298 Drugs Driveway,N,NaN,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876-678-3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876-678-3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,NaN,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,706-695-0392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,706-695-0392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,,N/a,N/a,Yes,Creed Braton
19,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [333]:
#Adding underscore ("_") to "Paying Customer" column name

df = df.rename(columns={'Paying Customer': 'Paying_Customer'})
df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123-643-9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,706-695-0392,298 Drugs Driveway,N,NaN,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876-678-3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876-678-3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,NaN,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,706-695-0392,2394 Hogwarts Avenue,Y,NaN,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,706-695-0392,3498 Super Lane,Y,NaN,Clark Kent
18,1019,,N/a,N/a,Yes,Creed Braton
19,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [335]:
#Working on NaN/Na from Paying_Customer and Do_Not_Contact columns

df['Paying_Customer'] = df['Paying_Customer'].apply(lambda x: '' if pd.isna(x) or pd.isnull(x) or str(x)=="N/a" else str(x))
df['Do_Not_Contact'] = df['Do_Not_Contact'].apply(lambda x: 'No' if pd.isna(x) or pd.isnull(x) or str(x)=="N/a" else str(x))
df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123-643-9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,706-695-0392,298 Drugs Driveway,N,No,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Dwight Schrute
4,1005,876-678-3469,123 Dragons Road,Y,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876-678-3469,98 Clue Drive,N,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,No,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,706-695-0392,2394 Hogwarts Avenue,Y,No,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,N,Don Draper
13,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,N,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,N,Ron Weasley
16,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,706-695-0392,3498 Super Lane,Y,No,Clark Kent
18,1019,,N/a,,Yes,Creed Braton
19,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,Anakin Skywalker

In [337]:
#Standardizing entries from Paying_Customer and Do_Not_Contact column entries.
df['Paying_Customer']= df['Paying_Customer'].apply(lambda x: ('Yes' if str(x).startswith('Y') else ('No' if str(x).startswith('N') else "")))

#Adding "No" to customers that did not specify if they wanted to be called.
df['Do_Not_Contact']= df['Do_Not_Contact'].apply(lambda x: ('Yes' if str(x).startswith('Y') else ('No')))
df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1002,123-643-9775,93 West Main Street,No,Yes,Abed Nadir
2,1003,706-695-0392,298 Drugs Driveway,No,No,Walter White
3,1004,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Yes,Dwight Schrute
4,1005,876-678-3469,123 Dragons Road,Yes,No,Jon Snow
5,1006,304-762-2467,768 City Parkway,Yes,Yes,Ron Swanson
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876-678-3469,98 Clue Drive,No,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,No,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,706-695-0392,2394 Hogwarts Avenue,Yes,No,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,No,Don Draper
13,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,No,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,No,Ron Weasley
16,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,706-695-0392,3498 Super Lane,Yes,No,Clark Kent
18,1019,,N/a,,Yes,Creed Braton
19,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,Anakin Skywalker

In [339]:
#Deleting from the list the customers that don't want to be called.

for x in df.index:
    if df.loc[x,'Do_Not_Contact'] == 'Yes':
        df.drop(x, inplace = True)
df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
2,1003,706-695-0392,298 Drugs Driveway,No,No,Walter White
4,1005,876-678-3469,123 Dragons Road,Yes,No,Jon Snow
6,1007,,1209 South Street,No,No,Jeff Winger
7,1008,876-678-3469,98 Clue Drive,No,No,Sherlock Holmes
8,1009,,123 Middle Earth,Yes,No,Gandalf
9,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
10,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee
11,1012,706-695-0392,2394 Hogwarts Avenue,Yes,No,Harry Potter
12,1013,123-543-2345,2039 Main Street,Yes,No,Don Draper
13,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
14,1015,304-762-2467,214 HR Avenue,No,No,Toby Flenderson
15,1016,123-545-5421,2395 Hogwarts Avenue,No,No,Ron Weasley
16,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
17,1018,706-695-0392,3498 Super Lane,Yes,No,Clark Kent
19,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,Anakin Skywalker

In [341]:
#Creating a second data frame for customers whose phone number is missing.

Missing_Num_df = pd.DataFrame(columns =['CustomerID','Phone_Number','Address','Paying_Customer','Do_Not_Contact','Full_Name'])

for x in df.index:
    
    # Checking if the 'Phone_Number' column is empty
    if df.loc[x,'Phone_Number'] == '':
        
        #Adding those rows to a new dataframe 
        Missing_Num_df = Missing_Num_df._append(df.loc[x], ignore_index=True)
        
        #Droping those customers from the original dataframe
        df.drop(x, inplace=True)
        
Missing_Num_df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1007,,1209 South Street,No,No,Jeff Winger
1,1009,,123 Middle Earth,Yes,No,Gandalf
2,1011,,"612 Shire Lane, Shire",Yes,No,Samwise Gamgee

In [343]:
df= df.reset_index(drop=True)
df

,CustomerID,Phone_Number,Address,Paying_Customer,Do_Not_Contact,Full_Name
0,1001,123-545-5421,"123 Shire Lane, Shire",Yes,No,Frodo Baggins
1,1003,706-695-0392,298 Drugs Driveway,No,No,Walter White
2,1005,876-678-3469,123 Dragons Road,Yes,No,Jon Snow
3,1008,876-678-3469,98 Clue Drive,No,No,Sherlock Holmes
4,1010,123-545-5421,"25th Main Street, New York",Yes,No,Peter Parker
5,1012,706-695-0392,2394 Hogwarts Avenue,Yes,No,Harry Potter
6,1013,123-543-2345,2039 Main Street,Yes,No,Don Draper
7,1014,876-678-3469,343 City Parkway,Yes,No,Leslie Knope
8,1015,304-762-2467,214 HR Avenue,No,No,Toby Flenderson
9,1016,123-545-5421,2395 Hogwarts Avenue,No,No,Ron Weasley
10,1017,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Michael Scott
11,1018,706-695-0392,3498 Super Lane,Yes,No,Clark Kent
12,1020,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No,Anakin Skywalker

In [345]:
#Saving the list as CSV file.

df.to_csv('To_Call_list.csv')